//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace ConsoleApplication6.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EGUSReferenceSOAP", Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSReference : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EGUSAgreementUpdatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EGUSExchangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback EGUSExchangeProductGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback EGUSPartyOperationCompleted;
        
        private System.Threading.SendOrPostCallback EGUSExchangeFirmOperationCompleted;
        
        private System.Threading.SendOrPostCallback EGUSAgreementDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EGUSReference() {
            this.Url = global::ConsoleApplication6.Properties.Settings.Default.ConsoleApplication6_WebReference_EGUSReference;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EGUSAgreementUpdatesCompletedEventHandler EGUSAgreementUpdatesCompleted;
        
        /// <remarks/>
        public event EGUSExchangeCompletedEventHandler EGUSExchangeCompleted;
        
        /// <remarks/>
        public event EGUSExchangeProductGroupCompletedEventHandler EGUSExchangeProductGroupCompleted;
        
        /// <remarks/>
        public event EGUSPartyCompletedEventHandler EGUSPartyCompleted;
        
        /// <remarks/>
        public event EGUSExchangeFirmCompletedEventHandler EGUSExchangeFirmCompleted;
        
        /// <remarks/>
        public event EGUSAgreementDetailsCompletedEventHandler EGUSAgreementDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.markit.com/EGUS/EGUSAgreementUpdates", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("EGUSAgreementUpdatesResponse", Namespace="http://www.markit.com/EGUS/")]
        public EGUSAgreementUpdatesResponse EGUSAgreementUpdates([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.markit.com/EGUS/")] EGUSAgreementUpdatesRequest EGUSAgreementUpdatesRequest) {
            object[] results = this.Invoke("EGUSAgreementUpdates", new object[] {
                        EGUSAgreementUpdatesRequest});
            return ((EGUSAgreementUpdatesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void EGUSAgreementUpdatesAsync(EGUSAgreementUpdatesRequest EGUSAgreementUpdatesRequest) {
            this.EGUSAgreementUpdatesAsync(EGUSAgreementUpdatesRequest, null);
        }
        
        /// <remarks/>
        public void EGUSAgreementUpdatesAsync(EGUSAgreementUpdatesRequest EGUSAgreementUpdatesRequest, object userState) {
            if ((this.EGUSAgreementUpdatesOperationCompleted == null)) {
                this.EGUSAgreementUpdatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEGUSAgreementUpdatesOperationCompleted);
            }
            this.InvokeAsync("EGUSAgreementUpdates", new object[] {
                        EGUSAgreementUpdatesRequest}, this.EGUSAgreementUpdatesOperationCompleted, userState);
        }
        
        private void OnEGUSAgreementUpdatesOperationCompleted(object arg) {
            if ((this.EGUSAgreementUpdatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EGUSAgreementUpdatesCompleted(this, new EGUSAgreementUpdatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.markit.com/EGUS/EGUSExchange", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("EGUSExchangeResponse", Namespace="http://www.markit.com/EGUS/")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EGUSExchange[] EGUSExchange([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.markit.com/EGUS/")] EGUSExchangeRequest EGUSExchangeRequest) {
            object[] results = this.Invoke("EGUSExchange", new object[] {
                        EGUSExchangeRequest});
            return ((EGUSExchange[])(results[0]));
        }
        
        /// <remarks/>
        public void EGUSExchangeAsync(EGUSExchangeRequest EGUSExchangeRequest) {
            this.EGUSExchangeAsync(EGUSExchangeRequest, null);
        }
        
        /// <remarks/>
        public void EGUSExchangeAsync(EGUSExchangeRequest EGUSExchangeRequest, object userState) {
            if ((this.EGUSExchangeOperationCompleted == null)) {
                this.EGUSExchangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEGUSExchangeOperationCompleted);
            }
            this.InvokeAsync("EGUSExchange", new object[] {
                        EGUSExchangeRequest}, this.EGUSExchangeOperationCompleted, userState);
        }
        
        private void OnEGUSExchangeOperationCompleted(object arg) {
            if ((this.EGUSExchangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EGUSExchangeCompleted(this, new EGUSExchangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.markit.com/EGUS/EGUSExchangeProductGroup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("EGUSExchangeProductGroupResponse", Namespace="http://www.markit.com/EGUS/")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EGUSExchangeProductGroup[] EGUSExchangeProductGroup([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.markit.com/EGUS/")] EGUSExchangeProductGroupRequest EGUSExchangeProductGroupRequest) {
            object[] results = this.Invoke("EGUSExchangeProductGroup", new object[] {
                        EGUSExchangeProductGroupRequest});
            return ((EGUSExchangeProductGroup[])(results[0]));
        }
        
        /// <remarks/>
        public void EGUSExchangeProductGroupAsync(EGUSExchangeProductGroupRequest EGUSExchangeProductGroupRequest) {
            this.EGUSExchangeProductGroupAsync(EGUSExchangeProductGroupRequest, null);
        }
        
        /// <remarks/>
        public void EGUSExchangeProductGroupAsync(EGUSExchangeProductGroupRequest EGUSExchangeProductGroupRequest, object userState) {
            if ((this.EGUSExchangeProductGroupOperationCompleted == null)) {
                this.EGUSExchangeProductGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEGUSExchangeProductGroupOperationCompleted);
            }
            this.InvokeAsync("EGUSExchangeProductGroup", new object[] {
                        EGUSExchangeProductGroupRequest}, this.EGUSExchangeProductGroupOperationCompleted, userState);
        }
        
        private void OnEGUSExchangeProductGroupOperationCompleted(object arg) {
            if ((this.EGUSExchangeProductGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EGUSExchangeProductGroupCompleted(this, new EGUSExchangeProductGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.markit.com/EGUS/EGUSParty", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("EGUSPartyResponse", Namespace="http://www.markit.com/EGUS/")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EGUSParty[] EGUSParty([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.markit.com/EGUS/")] EGUSPartyRequest EGUSPartyRequest) {
            object[] results = this.Invoke("EGUSParty", new object[] {
                        EGUSPartyRequest});
            return ((EGUSParty[])(results[0]));
        }
        
        /// <remarks/>
        public void EGUSPartyAsync(EGUSPartyRequest EGUSPartyRequest) {
            this.EGUSPartyAsync(EGUSPartyRequest, null);
        }
        
        /// <remarks/>
        public void EGUSPartyAsync(EGUSPartyRequest EGUSPartyRequest, object userState) {
            if ((this.EGUSPartyOperationCompleted == null)) {
                this.EGUSPartyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEGUSPartyOperationCompleted);
            }
            this.InvokeAsync("EGUSParty", new object[] {
                        EGUSPartyRequest}, this.EGUSPartyOperationCompleted, userState);
        }
        
        private void OnEGUSPartyOperationCompleted(object arg) {
            if ((this.EGUSPartyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EGUSPartyCompleted(this, new EGUSPartyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.markit.com/EGUS/EGUSExchangeFirm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("EGUSExchangeFirmResponse", Namespace="http://www.markit.com/EGUS/")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EGUSExchangeFirm[] EGUSExchangeFirm([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.markit.com/EGUS/")] EGUSExchangeFirmRequest EGUSExchangeFirmRequest) {
            object[] results = this.Invoke("EGUSExchangeFirm", new object[] {
                        EGUSExchangeFirmRequest});
            return ((EGUSExchangeFirm[])(results[0]));
        }
        
        /// <remarks/>
        public void EGUSExchangeFirmAsync(EGUSExchangeFirmRequest EGUSExchangeFirmRequest) {
            this.EGUSExchangeFirmAsync(EGUSExchangeFirmRequest, null);
        }
        
        /// <remarks/>
        public void EGUSExchangeFirmAsync(EGUSExchangeFirmRequest EGUSExchangeFirmRequest, object userState) {
            if ((this.EGUSExchangeFirmOperationCompleted == null)) {
                this.EGUSExchangeFirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEGUSExchangeFirmOperationCompleted);
            }
            this.InvokeAsync("EGUSExchangeFirm", new object[] {
                        EGUSExchangeFirmRequest}, this.EGUSExchangeFirmOperationCompleted, userState);
        }
        
        private void OnEGUSExchangeFirmOperationCompleted(object arg) {
            if ((this.EGUSExchangeFirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EGUSExchangeFirmCompleted(this, new EGUSExchangeFirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.markitserv.com/2012/EGUS-AD-2-0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("EGUSAgreementDetailsResponse", Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
        public EGUSAgreementDetailsResponse EGUSAgreementDetails([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")] EGUSAgreementDetailsRequest EGUSAgreementDetailsRequest) {
            object[] results = this.Invoke("EGUSAgreementDetails", new object[] {
                        EGUSAgreementDetailsRequest});
            return ((EGUSAgreementDetailsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void EGUSAgreementDetailsAsync(EGUSAgreementDetailsRequest EGUSAgreementDetailsRequest) {
            this.EGUSAgreementDetailsAsync(EGUSAgreementDetailsRequest, null);
        }
        
        /// <remarks/>
        public void EGUSAgreementDetailsAsync(EGUSAgreementDetailsRequest EGUSAgreementDetailsRequest, object userState) {
            if ((this.EGUSAgreementDetailsOperationCompleted == null)) {
                this.EGUSAgreementDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEGUSAgreementDetailsOperationCompleted);
            }
            this.InvokeAsync("EGUSAgreementDetails", new object[] {
                        EGUSAgreementDetailsRequest}, this.EGUSAgreementDetailsOperationCompleted, userState);
        }
        
        private void OnEGUSAgreementDetailsOperationCompleted(object arg) {
            if ((this.EGUSAgreementDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EGUSAgreementDetailsCompleted(this, new EGUSAgreementDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSAgreementUpdatesRequest {
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime toDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public partial class ErrorType {
        
        private string errorCodeField;
        
        private string errorStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorString {
            get {
                return this.errorStringField;
            }
            set {
                this.errorStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public partial class Tier {
        
        private PeriodEnum periodField;
        
        private bool periodFieldSpecified;
        
        private ApplyToEnum applyToField;
        
        private bool applyToFieldSpecified;
        
        private StartTypeEnum startTypeField;
        
        private bool startTypeFieldSpecified;
        
        private decimal startTypeValueField;
        
        private bool startTypeValueFieldSpecified;
        
        private decimal tierAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PeriodEnum Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeriodSpecified {
            get {
                return this.periodFieldSpecified;
            }
            set {
                this.periodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApplyToEnum ApplyTo {
            get {
                return this.applyToField;
            }
            set {
                this.applyToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplyToSpecified {
            get {
                return this.applyToFieldSpecified;
            }
            set {
                this.applyToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StartTypeEnum StartType {
            get {
                return this.startTypeField;
            }
            set {
                this.startTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTypeSpecified {
            get {
                return this.startTypeFieldSpecified;
            }
            set {
                this.startTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal StartTypeValue {
            get {
                return this.startTypeValueField;
            }
            set {
                this.startTypeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTypeValueSpecified {
            get {
                return this.startTypeValueFieldSpecified;
            }
            set {
                this.startTypeValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TierAmount {
            get {
                return this.tierAmountField;
            }
            set {
                this.tierAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public enum PeriodEnum {
        
        /// <remarks/>
        Monthly,
        
        /// <remarks/>
        Daily,
        
        /// <remarks/>
        Trade,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public enum ApplyToEnum {
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        AT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public enum StartTypeEnum {
        
        /// <remarks/>
        Amount,
        
        /// <remarks/>
        Number,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public partial class RateType {
        
        private string productGroupCodeField;
        
        private string productCodeField;
        
        private string productTypeField;
        
        private int rankField;
        
        private bool rankFieldSpecified;
        
        private TradeTypeEnum tradeTypeField;
        
        private SpreadEnum spreadField;
        
        private RateTypeEnum rateType1Field;
        
        private string executionTypeField;
        
        private string executionTypeNameField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal minAmountField;
        
        private bool minAmountFieldSpecified;
        
        private decimal maxAmountField;
        
        private bool maxAmountFieldSpecified;
        
        private string rateCurrencyField;
        
        private Tier[] tiersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductGroupCode {
            get {
                return this.productGroupCodeField;
            }
            set {
                this.productGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RankSpecified {
            get {
                return this.rankFieldSpecified;
            }
            set {
                this.rankFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TradeTypeEnum TradeType {
            get {
                return this.tradeTypeField;
            }
            set {
                this.tradeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpreadEnum Spread {
            get {
                return this.spreadField;
            }
            set {
                this.spreadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RateType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RateTypeEnum RateType1 {
            get {
                return this.rateType1Field;
            }
            set {
                this.rateType1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExecutionType {
            get {
                return this.executionTypeField;
            }
            set {
                this.executionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExecutionTypeName {
            get {
                return this.executionTypeNameField;
            }
            set {
                this.executionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MinAmount {
            get {
                return this.minAmountField;
            }
            set {
                this.minAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinAmountSpecified {
            get {
                return this.minAmountFieldSpecified;
            }
            set {
                this.minAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MaxAmount {
            get {
                return this.maxAmountField;
            }
            set {
                this.maxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxAmountSpecified {
            get {
                return this.maxAmountFieldSpecified;
            }
            set {
                this.maxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RateCurrency {
            get {
                return this.rateCurrencyField;
            }
            set {
                this.rateCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Tier[] Tiers {
            get {
                return this.tiersField;
            }
            set {
                this.tiersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public enum TradeTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(" ")]
        Item,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        T,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public enum SpreadEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(" ")]
        Item,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public enum RateTypeEnum {
        
        /// <remarks/>
        Rate,
        
        /// <remarks/>
        Flat,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Vol Disc")]
        VolDisc,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("%Premium")]
        Premium,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("%Notion")]
        Notion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public partial class Exchange {
        
        private RateType[] rateField;
        
        private string exchangeCodeField;
        
        private YesNoEnum directBillField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RateType[] Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExchangeCode {
            get {
                return this.exchangeCodeField;
            }
            set {
                this.exchangeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public YesNoEnum DirectBill {
            get {
                return this.directBillField;
            }
            set {
                this.directBillField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-COMMON-2-0")]
    public enum YesNoEnum {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public partial class RateScheduleType {
        
        private AccountType[] executingAccountsField;
        
        private Exchange[] exchangesField;
        
        private string rateScheduleIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Account", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AccountType[] ExecutingAccounts {
            get {
                return this.executingAccountsField;
            }
            set {
                this.executingAccountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Exchange[] Exchanges {
            get {
                return this.exchangesField;
            }
            set {
                this.exchangesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RateScheduleId {
            get {
                return this.rateScheduleIdField;
            }
            set {
                this.rateScheduleIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public partial class AccountType {
        
        private string descriptionField;
        
        private System.DateTime effectiveDateField;
        
        private bool effectiveDateFieldSpecified;
        
        private System.Nullable<System.DateTime> expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        private string[] linkedToClearingAccountField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveDateSpecified {
            get {
                return this.effectiveDateFieldSpecified;
            }
            set {
                this.effectiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified {
            get {
                return this.expirationDateFieldSpecified;
            }
            set {
                this.expirationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LinkedToClearingAccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] LinkedToClearingAccount {
            get {
                return this.linkedToClearingAccountField;
            }
            set {
                this.linkedToClearingAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public partial class ExchangeFirmCodeType {
        
        private string exchangeCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExchangeCode {
            get {
                return this.exchangeCodeField;
            }
            set {
                this.exchangeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public partial class AgreementDetailsType {
        
        private string customerReferenceField;
        
        private string agreementTypeField;
        
        private string statusField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime approvalDateField;
        
        private System.DateTime updateDateField;
        
        private System.DateTime effectiveDateField;
        
        private System.Nullable<System.DateTime> terminationDateField;
        
        private bool terminationDateFieldSpecified;
        
        private BillWhoEnum billWhoField;
        
        private string profitCenterField;
        
        private PartiesTypeParty[] partiesField;
        
        private AccountType[] clearingAccountsField;
        
        private RateScheduleType[] rateSchedulesField;
        
        private string agreementIdField;
        
        private string groupIdField;
        
        private string priorAgreementIDField;
        
        private NewOrChangeEnum newOrChangeField;
        
        public AgreementDetailsType() {
            this.newOrChangeField = NewOrChangeEnum.@new;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AgreementType {
            get {
                return this.agreementTypeField;
            }
            set {
                this.agreementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ApprovalDate {
            get {
                return this.approvalDateField;
            }
            set {
                this.approvalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> TerminationDate {
            get {
                return this.terminationDateField;
            }
            set {
                this.terminationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TerminationDateSpecified {
            get {
                return this.terminationDateFieldSpecified;
            }
            set {
                this.terminationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BillWhoEnum BillWho {
            get {
                return this.billWhoField;
            }
            set {
                this.billWhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProfitCenter {
            get {
                return this.profitCenterField;
            }
            set {
                this.profitCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Party", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PartiesTypeParty[] Parties {
            get {
                return this.partiesField;
            }
            set {
                this.partiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Account", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AccountType[] ClearingAccounts {
            get {
                return this.clearingAccountsField;
            }
            set {
                this.clearingAccountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RateSchedule", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RateScheduleType[] RateSchedules {
            get {
                return this.rateSchedulesField;
            }
            set {
                this.rateSchedulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AgreementId {
            get {
                return this.agreementIdField;
            }
            set {
                this.agreementIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PriorAgreementID {
            get {
                return this.priorAgreementIDField;
            }
            set {
                this.priorAgreementIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(NewOrChangeEnum.@new)]
        public NewOrChangeEnum NewOrChange {
            get {
                return this.newOrChangeField;
            }
            set {
                this.newOrChangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public enum BillWhoEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Clearing Broker")]
        ClearingBroker,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Trader,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public partial class PartiesTypeParty {
        
        private string nameField;
        
        private PartyTypeEnum typeField;
        
        private ExchangeFirmCodeType[] exchangeFirmCodeField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyTypeEnum Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExchangeFirmCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExchangeFirmCodeType[] ExchangeFirmCode {
            get {
                return this.exchangeFirmCodeField;
            }
            set {
                this.exchangeFirmCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public enum PartyTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Clearing Broker")]
        ClearingBroker,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Executing Broker")]
        ExecutingBroker,
        
        /// <remarks/>
        Trader,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Carrying Broker")]
        CarryingBroker,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LME Executing Member")]
        LMEExecutingMember,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Additional Trader")]
        AdditionalTrader,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Order Passing Broker (aka: Order Placement Agent)")]
        OrderPassingBrokerakaOrderPlacementAgent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Clearing Administrative Clearer")]
        ClearingAdministrativeClearer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Executing Administrative Clearer")]
        ExecutingAdministrativeClearer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public enum NewOrChangeEnum {
        
        /// <remarks/>
        @new,
        
        /// <remarks/>
        change,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/")]
    public partial class Firm {
        
        private string firmCodeField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime updateDateField;
        
        private string primaryFlagField;
        
        private string exchangeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirmCode {
            get {
                return this.firmCodeField;
            }
            set {
                this.firmCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrimaryFlag {
            get {
                return this.primaryFlagField;
            }
            set {
                this.primaryFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExchangeCode {
            get {
                return this.exchangeCodeField;
            }
            set {
                this.exchangeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSExchangeFirm {
        
        private Firm[] firmField;
        
        private string partyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Firm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Firm[] Firm {
            get {
                return this.firmField;
            }
            set {
                this.firmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PartyCode {
            get {
                return this.partyCodeField;
            }
            set {
                this.partyCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSParty {
        
        private string nameField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime updateDateField;
        
        private string partyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PartyCode {
            get {
                return this.partyCodeField;
            }
            set {
                this.partyCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/")]
    public partial class Product {
        
        private string productNameField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime updateDateField;
        
        private string productCodeField;
        
        private string productTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/")]
    public partial class ProductGroup {
        
        private string productGroupNameField;
        
        private Product[] productField;
        
        private string productGroupCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductGroupName {
            get {
                return this.productGroupNameField;
            }
            set {
                this.productGroupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Product", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Product[] Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductGroupCode {
            get {
                return this.productGroupCodeField;
            }
            set {
                this.productGroupCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSExchangeProductGroup {
        
        private ProductGroup[] productGroupField;
        
        private string exchangeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductGroup[] ProductGroup {
            get {
                return this.productGroupField;
            }
            set {
                this.productGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExchangeCode {
            get {
                return this.exchangeCodeField;
            }
            set {
                this.exchangeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSExchange {
        
        private string nameField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime updateDateField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/")]
    public partial class Agreement {
        
        private System.DateTime updateDateField;
        
        private System.DateTime effectiveDateField;
        
        private System.DateTime terminationDateField;
        
        private bool terminationDateFieldSpecified;
        
        private int agreementIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime TerminationDate {
            get {
                return this.terminationDateField;
            }
            set {
                this.terminationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TerminationDateSpecified {
            get {
                return this.terminationDateFieldSpecified;
            }
            set {
                this.terminationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AgreementId {
            get {
                return this.agreementIdField;
            }
            set {
                this.agreementIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSAgreementUpdatesResponse {
        
        private Agreement[] agreementField;
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Agreement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Agreement[] Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime toDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSExchangeRequest {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("fromDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("toDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Code")]
        Code,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":fromDate")]
        fromDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":toDate")]
        toDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSExchangeProductGroupRequest {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExchangeCode", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("fromDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("toDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ExchangeCode")]
        ExchangeCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":fromDate")]
        fromDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":toDate")]
        toDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSPartyRequest {
        
        private object[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PartyCode", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("fromDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("toDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":PartyCode")]
        PartyCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":fromDate")]
        fromDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":toDate")]
        toDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markit.com/EGUS/")]
    public partial class EGUSExchangeFirmRequest {
        
        private object[] itemsField;
        
        private ItemsChoiceType3[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PartyCode", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("fromDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("toDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType3[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markit.com/EGUS/", IncludeInSchema=false)]
    public enum ItemsChoiceType3 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":PartyCode")]
        PartyCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":fromDate")]
        fromDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":toDate")]
        toDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public partial class EGUSAgreementDetailsRequest {
        
        private object[] itemsField;
        
        private ItemsChoiceType4[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("agreementId", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("fromDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("toDate", typeof(System.DateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType4[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0", IncludeInSchema=false)]
    public enum ItemsChoiceType4 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":agreementId")]
        agreementId,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":fromDate")]
        fromDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":toDate")]
        toDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.markitserv.com/2012/EGUS-AD-2-0")]
    public partial class EGUSAgreementDetailsResponse {
        
        private AgreementDetailsType[] agreementDetailsField;
        
        private ErrorType errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AgreementDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AgreementDetailsType[] AgreementDetails {
            get {
                return this.agreementDetailsField;
            }
            set {
                this.agreementDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ErrorType Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EGUSAgreementUpdatesCompletedEventHandler(object sender, EGUSAgreementUpdatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EGUSAgreementUpdatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EGUSAgreementUpdatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EGUSAgreementUpdatesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EGUSAgreementUpdatesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EGUSExchangeCompletedEventHandler(object sender, EGUSExchangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EGUSExchangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EGUSExchangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EGUSExchange[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EGUSExchange[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EGUSExchangeProductGroupCompletedEventHandler(object sender, EGUSExchangeProductGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EGUSExchangeProductGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EGUSExchangeProductGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EGUSExchangeProductGroup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EGUSExchangeProductGroup[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EGUSPartyCompletedEventHandler(object sender, EGUSPartyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EGUSPartyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EGUSPartyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EGUSParty[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EGUSParty[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EGUSExchangeFirmCompletedEventHandler(object sender, EGUSExchangeFirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EGUSExchangeFirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EGUSExchangeFirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EGUSExchangeFirm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EGUSExchangeFirm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EGUSAgreementDetailsCompletedEventHandler(object sender, EGUSAgreementDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EGUSAgreementDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EGUSAgreementDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EGUSAgreementDetailsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EGUSAgreementDetailsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591